spring.main.banner-mode=off

logging.level.root=ERROR
logging.level.com.websec=INFO

scanner.http.timeout=5000

scanner.subdomain.max=50

scanner.http.user-agent=WebSec-Scanner/1.0 (Educational Tool)

spring.application.name=websec-scanner